name: FRONTEND Analysis and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend/client

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: ./.github/actions/setup_flutter.yml
      
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .
      
      - name: Analyze project
        run: flutter analyze --no-fatal-warnings

      - name: Run tests
        run: flutter test